services:
  db_sql:
    image: mysql:8.0
    restart: always
    container_name: conteneur_BD
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - ./data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - prod-network

  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer_db
    ports:
      - "${PORT_ADMINER}:8080"
    depends_on:
      - db_sql
    environment:
      ADMINER_DEFAULT_SERVER: db_sql
    networks:
      - prod-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_bd
    restart: always
    volumes: 
      - ./data_portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${PORT_PORTAINER}:9443"
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge